### PR TITLE
Add circuit optimization and docs

### PR DESCRIPTION
**Pull request by rmlarose**
Adds a simple circuit optimization and doc showing a benchmark. We should add more to the optimize function, but this is a start.

### CODE REVIEW

**Comment by rmlarose** [comment]
Seeing some flakes in unit tests for simulating noise - should be independent of this but addressed in a separate issue/PR.

**Comment by asciineuron** [comment]
Awesome this is a really nice speedup. Only case we might want to warn against using it is on near-clifford circuits, since merging T gates with Clifford gates would yield weird gates that aren't supported by `act_on_near_clifford`

**Review by asciineuron — APPROVED** [review]
Awesome this is a really nice speedup. Only case we might want to warn against using it is on near-clifford circuits, since merging T gates with Clifford gates would yield weird gates that aren't supported by act_on_near_clifford

**Comment by rmlarose** [comment]
> Only case we might want to warn against using it is on near-clifford circuits, since merging T gates with Clifford gates would yield weird gates that aren't supported by act_on_near_clifford

Great point! Added a short note about this in the doc.

**Pull request merged**
